# Generated by Django 4.2 on 2023-06-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_bookedseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_booked_seats', to='movies.movie'),
        ),
    ]
