# Generated by Django 4.2 on 2023-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_bookedseatdetail_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseatdetail',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
